spring:
  application:
    name: @pom.artifactId@

eureka:
  server:
    #关闭自我保护，开发环境下关闭
    enable-self-preservation: false
    #清理间隔，默认60000ms，开发环境下修改为5000ms
    eviction-interval-timer-in-ms: 5000
    #节点间读数据连接超时时间
    peer-node-read-timeout-ms: 200
  client:
    serviceUrl:
      defauleZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2